name: Terraform Plan Exit Code Test

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan with Exit Code Detection
        id: plan
        continue-on-error: true
        run: |
          cd terraform-test
          terraform plan -detailed-exitcode -out=tf.plan
          exit_code=$?
          echo "Terraform plan exit code: $exit_code"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

          if [ "$exit_code" -eq 2 ]; then
            echo "Changes detected."
          elif [ "$exit_code" -eq 0 ]; then
            echo "No changes detected."
          else
            echo "Terraform plan failed."
            exit 1
          fi

      - name: Show captured exit code from plan step
        run: |
          echo "Captured exit code: ${{ steps.plan.outputs.exit_code }}"
